version: 2.1
workflows:
  build_and_dock:
    jobs:
      - build
      - dock:
          context: Perso
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    working_directory: ~/theater-vote
    steps:
      - checkout
      - restore_cache:
          keys:
            - tp1-api-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: app-{{ checksum "pom.xml" }}
      # package into a jar
      - run: mvn clean install
      - run: mvn clean package
        # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: theater-vote
  dock:
    docker:
      - image: circleci/openjdk:latest
    working_directory: ~/theater-vote
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ checksum "pom.xml" }}
      # build and push docker image to docker hub
      - run: mvn compile jib:build -Djib.to.auth.username="pdarcasssss" -Djib.to.auth.password=$DOCKERHUB_PASSWORD